spring.application.name=ecommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/customer_db
spring.datasource.username=postgres
spring.datasource.password=
springgi.jpa.hibernate.ddl-auto=update